- Makefile.am
- configure.ac
- m4/ax_check_compile_flag.m4
- m4/ax_check_link_flag.m4
- scripts/wrap-compiler-for-flag-check
Many compilers enable some kind of hardening by default, but this is not universally the case, and some more aggressive options are not always enabled.
There may be a performance impact to -fstack-protector-all by default, but Chromium uses this option when -fstack-protector-strong is not available, and I think that is appropriate for a critical security component.
> Turn on memory corruption hardening where available

- configure.ac
- update.sh
Hi,
I'd like to add support for Cygwin to libressl portable, slowly and
carefully.  For a start I'd like to propose the below patch.  It allows
to build with the default hardening without having to specify
--enable-windows-ssp.  Other than that change, libressl-portable builds
out of the box on Cygwin 1.7.35, the upcoming release later this week. 
The reason it needs 1.7.35 is the existence of the issetugid function.
The functionality existed for a long time, it was just never exported so far.
Unfortunately the testsuite doesn't build on Cygwin, because the testsuite
requires SA_ONSTACK and sigaltstack to work, functionality not available
yet on Cygwin.  But that's another issue.
Thanks,
Corinna
Signed-off-by: Corinna Vinschen <github@cygwin.de>
> Add preliminary Cygwin support

- configure.ac
It enables (for now) the system-wide reallocarray(3) and strtonum(3).
> Reuse _OPENBSD_SOURCE namespace on NetBSD (>=8.x)

- configure.ac
this PR is for https://github.com/libressl-portable/portable/issues/81
Thanks.
> modify for HP-UX build, choose correct CFLAGS for gcc.

- apps/Makefile.am
- configure.ac
- update.sh
This is a work-in-progress patch to automatically install an openssl.cnf file into OPENSSLDIR, which itself will default to sysconfdir to simplify packaging.
This should also probably modify openssl.1 to point to the right path on install.
> install a default openssl.cnf

- m4/check-os-options.m4
to disable strict aliasing on HP-UX C/aC++, `+Otype_safety=off` is right.
`+Otype_safety=strong` forces ANSI aliasing.
> disable strict aliasing on HP-UX C/aC++ compiler

- update.sh
for issue https://github.com/libressl-portable/portable/issues/127 .
> use CP_LIBC for copying tests/memmem.c

- crypto/compat/posix_win.c
- include/compat/stdio.h
The gets(3) implementation on Windows includes the trailing characters '\r\n' in the returned stream, but the string handling code in openssl(1) generally expects '\n'.
This fixes #159, but unfortunately means that additionally things like password prompts had been including the '\r' in the resulting passwords when they got processed as well.
> wrap gets(3) on Windows, replacing '\r\n' with '\n'

- crypto/compat/ui_openssl_win.c
Replace STDIN_FILENO with _fileno as STDIN_FILENO results in compile
errors with Visual Studio 2015 (using CMake).
> Replace STDIN_FILENO with _fileno

- include/compat/netinet/ip.h
Hi,
I had this build error on HP-UX 11iv3 (11.31) with GCC 4.7.1 and HP C/aC++ A.06.25, both.
<pre>
...
CC       netcat.o
"/usr/include/netinet/ip.h", line 123: error #2020: identifier "n_long" is
undefined
n_long  ipt_time[1];
^
"/usr/include/netinet/ip.h", line 126: error #2020: identifier "n_long" is
undefined
n_long ipt_time;
^
2 errors detected in the compilation of "netcat.c".
*** Error exit code 2
</pre>
`n_long` is defined in `netinet/in_systm.h` on HP-UX 11iv3.
Could you add including <netinet/in_systm.h> in include/compat/netinet/ip.h ?
Thanks.
> build failed on HP-UX 11iv3 (11.31) for undefined u_long in netinet/ip.h

- CMakeLists.txt
`OBJECT` library type of add_library was introduced by CMake 2.8.8.
> set cmake_minimum_required to 2.8.8

- tests/CMakeLists.txt
- tests/ssltest.sh
- tests/testdsa.sh
- tests/testenc.sh
- tests/testrsa.sh
- uncomment procedures for aeadtest, evptest, pq_test, ssltest, testdsa and testrsa
- add set_tests_properties() for setting environment variable srcdir
- tweak openssl path in ssltest.sh, testdsa.sh, testenc.sh and testrsa.sh
> execute tests that require srcdir environment variable with cmake

- CMakeLists.txt
- apps/nc/CMakeLists.txt
- apps/openssl/CMakeLists.txt
- crypto/CMakeLists.txt
- tests/CMakeLists.txt
- tls/CMakeLists.txt
- add cmake build options as configure provides
* -DENABLE_ASM (default ON)
* -DENABLE_EXTRATESTS (default OFF)
* -DENABLE_NC (default OFF)
* -DOPENSSLDIR (default ${CMAKE_INSTALL_PREFIX}/etc/ssl)
- add biotest and pidwraptest if ENABLE_EXTRATESTS is ON
> add cmake build options

- apps/nc/Makefile.am
- apps/openssl/Makefile.am
- ssl/Makefile.am
- tests/Makefile.am
- tls/Makefile.am
- To avoid ld warning on Solaris, use abs_top_builddir in Makefile.am
On Solaris11.3(i386) I'm getting ld warning "attempted multiple inclusion of file" like below.
<pre>
...
CCLD   openssl
ld: warning: file ../../crypto/.libs/libcrypto.so: linked to /work/github/libressl-2.4.0/crypto/.libs/libcrypto.so: attempted multiple inclusion of file
...
</pre>
This warning comes from Solaris ld can't tell `../../crypto/.libs/libcrypto.so` and `/work/github/libressl-2.4.0/crypto/.libs/libcrypto.so` are the same library.
openssl is defined that it should be linked with $(top_builddir)/ssl/libssl.la and $(top_builddir)/crypto/libcrypto.la in apps/openssl/Makefile.am .
And libtool seems try to link libraries at dependency_libs in .la files, too.
In ssl/libssl.la, libcrypto.la is described as absolute …
> fix ld warning "attempted multiple inclusion of file" on Solaris

- libcrypto.pc.in
- libssl.pc.in
- libtls.pc.in
Fixes compilations including libressl static libraries in MinGW.
Signed-off-by: Ricardo Constantino (:RiCON) <wiiaboo@gmail.com>
> pc: add platform-specific libs to Libs.private

- m4/check-libc.m4
Solaris 11 recently introduced a builtin arc4random in libc which fails the tests in "make check". Found USE_BUILTIN_ARC4RANDOM, but could not get it to work. Apparently, there is a typo in the configure logic rendering USE_BUILTIN_ARC4RANDOM ineffective.
> Fix typo in USE_BUILTIN_ARC4RANDOM check

- tests/CMakeLists.txt
Currently on cmake builds, make test shows the OCSP tests as failing if /etc/ssl/cert.pem does not exist. This change to CMakeLists.txt defines _PATH_SSL_CA_FILE to a sane value if either OPENSSLDIR or CMAKE_INSTALL_PREFIX is set so that these tests can run successfully without a system-installed libressl.
> Set _PATH_SSL_CA_FILE for the OCSP tests in the cmake build system

- tests/CMakeLists.txt
- tests/Makefile.am
- let tests to use the cert.pem in the tarball, for both automake and cmake.
- put this definition out of "if(ENABLE_EXTRATESTS)" since this can be shared by all tests.
As discussions in the PR https://github.com/libressl-portable/portable/pull/213 .
> Set _PATH_SSL_CA_FILE to the tarball internal path for regression tests

- .gitignore
- tests/CMakeLists.txt
- tests/Makefile.am
- add tls_ext_alpn entry for automake and cmake
- add tests/tls_ext_alpn* to .gitignore
> enable tls_ext_alpn regression test

- CMakeLists.txt
- Makefile.am.common
- crypto/CMakeLists.txt
This fixes the remaining assembly preprocessor and hidden symbol fallout with cmake and autotools builds.
> Fix the rest of the current build failures

- m4/check-libc.m4
- m4/check-os-options.m4
This diff changes the logic by which configure detects getentropy() to
ensure that we don't use the system wide getentropy
- with macOS sierra if the deployment target is lower than sierra as
found by tor developers here
https://gitweb.torproject.org/tor.git/commit/?id=https://gitweb.torproject.org/tor.git/commit/?id=16fcbd21c963a9a65bf55024680c8323c8b7175d
- with iOS unconditionally because an app linking libressl compiled with
system wide getentropy has been rejected by the App store as I have
documented here
https://github.com/measurement-kit/measurement-kit/pull/994
I think something similar could also affect clock_gettime judging from
tor's patch, but this diff for now doesn't address that.
I do not have macOS < sierra, so I could only verify that configure was
not picking up system …
> configure: fix getentropy() for sierra and ios

- CMakeLists.txt
- crypto/compat/posix_win.c
- crypto/crypto_win.list
- include/Makefile.am
- include/compat/err.h
- include/compat/fcntl.h
- include/compat/stdio.h
- include/compat/sys/socket.h
- include/compat/unistd.h
- include/compat/win32netcompat.h
- m4/check-libc.m4
- tests/CMakeLists.txt
- tests/Makefile.am
- tests/compat/pipe2.c
- tests/ssltest.bat
- tests/tlstest.bat
- tests/tlstest.sh
This is disabled for now on Windows for now due to pipe2/socketpair support, but I think it can be emulated without too much issue. Based on @kinichiro 's work on ssltest
> enable tlstest

- include/compat/fcntl.h
- include/compat/sys/stat.h
- S_IRGRP and S_IROTH should be defined in sys/stat.h rather than fcntl.h
- Old MinGW64 on Ubuntu 14.04 appears not to have S_IRGRP and S_IROTH
- MinGW64 has __WIN32 defined but does not have _MSC_VER defined
> Move S_IRGRP and S_IROTH from fcntl.h to sys/stat.h

- patches/tls.h.patch
This PR is proposal for issue https://github.com/libressl-portable/portable/issues/282.
> Add definition of ssize_t to tls.h for Windows

- README.windows
- configure.ac
Followup from https://github.com/libressl-portable/portable/pull/286
> Document 32-bit time_t problem on minw-w64 toolchain and how to avoid it

- crypto/CMakeLists.txt
- m4/check-libc.m4
- Fix the condition of exporting getentropy
- Modify the CMake condition of including arc4random_uniform as same as autoconf
> Fix condition of arc4random* and getentropy for Cygwin build

- crypto/Makefile.am
- m4/check-libc.m4
Generated files should be in the builddir rather than the srcdir. Because we're currently generating the file in configure's context, $builddir is not yet available. We should probably actually move the generation process to crypto/Makefile.am as well.
Fixes #300
> move crypto_portable.sym to builddir

- libcrypto.pc.in
It looks like this was copied and pasted from libssl.pc.in. This patch
identifies it as libcrypto rather than libssl.
> Fix pkg-config metadata for libcrypto

- .gitignore
- crypto/CMakeLists.txt
- crypto/Makefile.am
- crypto/compat/freezero.c
- include/compat/stdlib.h
- m4/check-libc.m4
Hi,
This PR provides freezero() for portable.
freezero() is placed in malloc.c in OpenBSD source tree.
I added simple freezero.c bits rather than copying malloc.s from openbsd/src/lib/libc/stdlib/.
Thanks.
> Add freezero support

- m4/check-libc.m4
This fixes #305 by only exporting OPENSSL_ia32cap_P where it is compiled.
> Only include ia32 symbols in export list on Intel architectures

- update.sh
With this modification, we can build portable with /usr/src easily.
> Modify update.sh to change the path of openbsd source tree easily

- crypto/CMakeLists.txt
- crypto/Makefile.am
- include/compat/sys/types.h
- tests/CMakeLists.txt
- tests/Makefile.am
- update.sh
- Add 1st step of hkdf function
- Add in_addr_t in include/compat/sys/types.h for Windows build
> Add hkdf and Add in_addr_t for Windows

- CMakeLists.txt
Need to search the current directory, not the overall project root directory
if this is being included as a sub-dependency of another project.
> Fix CMake module include path

- m4/check-os-options.m4
- define _GNU_SOURCE in case of cygwin
As compilation warning report by @Dravion
> add prototype definitions of asprintf and vasprintf for CYGWIN build

- patches/tlsexttest.c.patch
Some compiler does not support 0 sized array.
This patch changes 0 sized array to have NULL and using variable instead of
sizeof function.
This might not the best way, but this solves the compilation error on Visual Studio.
Using variable instead of just 0, to indicate explicitly it is the size of array.
Any other good advices are appreciated.
> Add patch for regress tlsexttest

- CMakeLists.txt
- include/CMakeLists.txt
pqueue.h was getting installed when it shouldn't.
pkgconfig files were not getting installed or generated.
links to manual pages are also not being installed, but I'm not sure where to get a list of those links when I'm inside the tarball.
> Some CMake Fixes.

- patches/netcat.c.patch
If the target system does not define IPV6_TCLASS, this part of
the patch handles that with an ENOPROTOOPT error rather than
failing to compile.
Unfortunately it's missing a trailing semicolon leading to
a compilation error.
Add the missing semicolon to fix the problem.
Signed-off-by: Kyle J. McKay <mackyle@gmail.com>
---
Note that the original version of this patch was formatted slightly differently and it seems that during the reformatting a syntax error was introduced.
Would it be possible to pick this fix up for the next portable release?
> netcat.c.patch: eliminate syntax error from patch

- patches/tlsexttest.c.patch
- Windows and hp-ux ANSI compiler can not handle 0 sized array initialization.
> Modify regress tests/tlsexttest.c for 0 sized array

- include/compat/err.h
- This fix MSVC compiler warning C4702 "unreachable code".
> Call va_end soon after using variable length variable

- CMakeLists.txt
- Remove C4242 and C4820
- Warning explanation from manual
- Sort by warning code
> Reconsider MSVC warning list

- include/compat/sys/stat.h
- include/compat/sys/types.h
- tls/CMakeLists.txt
- tls/Makefile.am
- This PR solves linux and OSX build fail
- Added file permission define required by Windows and MinGW
- For Windows and MinGW build, need pread(), pwrite(), ftruncate() and gituid().
> Add tls/tls_keypair.c

- crypto/CMakeLists.txt
- crypto/Makefile.am
- include/compat/sys/types.h
- include/compat/unistd.h
- tls/CMakeLists.txt
- tls/Makefile.am
- tls/compat/ftruncate.c
- tls/compat/getuid.c
- tls/compat/pread.c
- tls/compat/pwrite.c
This is temporary solution to prevent build break of libtls on Windows platform.
It is just replacing posix functions with Windows suitable one.
We might have more high level solutions for this, but now I would like to solve build first.
I verified pread() and pwrite() with this test code.
https://gist.github.com/kinichiro/63d6262c5cdb3e0fe0bd5d0233a5ea03
I would appreciate any comments and suggestions.
> Add compat bits for libtls on Windows

- patches/keypairtest.c.patch
- patches/tls_config.c.patch
- patches/tls_util.c.patch
- tests/CMakeLists.txt
- tls/compat/ftruncate.c
- tls/compat/getuid.c
- tls/compat/pread.c
- tls/compat/pwrite.c
After investigating keypairtest issue with Visual Studio, I found that it used `posix_open` and `posix_read` for file descriptor instead of using `open` and `read` .
This PR fix that and bring back keypairtest with Visual Studio, again.
> Fix using right functions for file descriptor with MS Visual Studio

- crypto/CMakeLists.txt
- crypto/Makefile.am
- include/compat/pthread.h
- ssl/CMakeLists.txt
- ssl/Makefile.am
This adds Windows support on current builds and adds new _init files.
> Windows updates - add pthread_self/equal and pull in new init symbols

- appveyor.yml
LibreSSL does not have a Visual Studio build so its not clear if the CMake build works for it. This adds [AppVeyor](https://www.appveyor.com/) which is free for open source and has a Windows stack available for it.
> Add appveyor support for Window CI/CD

- appveyor.yml
On AppVeyor `ssltest` will not run so it should be turned off until it can be run successfully.
> Turn off ssltest on AppVeyor

- CMakeLists.txt
- README.md
- appveyor.yml
- crypto/CMakeLists.txt
- scripts/travis
- ssl/CMakeLists.txt
- tests/CMakeLists.txt
- tls/CMakeLists.txt
Removes custom logic for shared libraries and instead uses [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/v3.11/variable/BUILD_SHARED_LIBS.html) which is available in 2.8.8.
> Use BUILD_SHARED_LIBS to specify library type

- CMakeLists.txt
We added a general check for clock_gettime when it became required for all builds. This needs to be isolated from the Linux check, since it also needs to check whether -lrt needs to be added to linker flags.
Fixes #416
> better separate linux and non-linux checks for clock_gettime

- configure.ac
- include/compat/sys/types.h
On some targets ';' (like hppa) is treated as a comment
in assembly files. This occasionally causes the following
assembly failures:
```
Error: can't resolve `.gnu.warning.EVP_DecryptFinal'
{.gnu.warning.EVP_DecryptFinal section} - `.Ltext0' {.text section}
```
Note how branch (or other reference) attempts to cross the
boundary across two section types: '.text' and '.gnu.warning'.
Tobias Ulmer notes that openbsd already uses newlines
for similar macro:
https://github.com/openbsd/src/blob/master/sys/arch/hppa/include/cdefs.h
This change switches from ';' to newline as well.
Tested on hppa2.0 and x86_64.
Reported-by: Jeroen Roovers
Bug: https://bugs.gentoo.org/656104
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>
> __warn_references: tweak assembly for "gnu.warning" section

- patches/windows_headers.patch
Suppress "overriding WinCrypt defines" from openssl/x509.h by defining `NOCRYPT`.
Only this file does not check `__WINCRYPT_H__` macro like other headers, since
https://github.com/libressl-portable/portable/commit/5d8a1cf7155130bd8101090d7e1d0c2f90d9b123#diff-74b6370bc092dd2988ab577b2eaa21dcR7
> Suppress "overriding WinCrypt defines" warnings

- .gitignore
- crypto/CMakeLists.txt
- crypto/Makefile.am
- crypto/compat/crypto_lock_win.c
- update.sh
This is a modification of #477 from @johnex that uses an atomic swap to perform initialization as-needed. This is the same as how arc4random lock initialization works in arc4random_win.h
Fixes #478
> adjust Windows locks for auto-initialization

- crypto/compat/getpagesize.c
Fix #479. We added stricter checks for getpagesize existing in #475, which check that there is an actual header definition. mingw-w64 appears to export getpagesize as a symbol, but it does not expose the header, so depending on how we configure it, we may not detect mingw's implementation of getpagesize. This switches the check in the headers to work for Visual Studio or mingw-w64 by building the Windows path on any Windows platform.
> enable getpagesize for all Windows builds

- include/compat/stdint.h
This adds a workaround shim for some Android SDKs where SIZE_MAX is defined in limits.h instead of stdint.h.
See #482, this is a speculative diff, I haven't tested it.
> add stdint.h shim, include limits for SIZE_MAX on Android

- .travis.yml
- crypto/Makefile.am
- scripts/travis
This PR adds ARM32 and ARM64 build by Travis-CI.
Regression tests are executed under QEMU.
Include ARM header file within distribution package.
> Add ARM build

- crypto/compat/crypto_lock_win.c
Locks are required for multi-threading. If memory can't be allocated, exit the program with memory error. If we let the program continue, it will deadlock in the next part of the code anyway so better end it before.
> Handle malloc returning null

- CMakeLists.txt
- include/compat/time.h
- m4/check-libc.m4
This should fix #494 by adding a configure-time check for timespecsub. Since this is more often a macro, it still includes a preprocessor check, which is more difficult to do with CMake than autoconf.
> add configure-time check for timespecsub

- ChangeLog
- crypto/CMakeLists.txt
- crypto/Makefile.am
- tests/CMakeLists.txt
- tests/Makefile.am
- update.sh
Here is the companion to https://github.com/libressl-portable/openbsd/pull/103.
This is a contribution from [Ribose Inc](https://www.ribose.com) (@riboseinc).
> Add portable scaffold for SM4

- apps/openssl/CMakeLists.txt
On El Capitan:
[exec] [100%] Linking C executable openssl
[exec] Undefined symbols for architecture x86_64:
[exec]   "_clock_gettime", referenced from:
[exec]       _app_timer_real in apps_posix.c.o
[exec] ld: symbol(s) not found for architecture x86_64
[exec] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[exec] make[2]: *** [apps/openssl/openssl] Error 1
[exec] make[1]: *** [apps/openssl/CMakeFiles/openssl.dir/all] Error 2
[exec] make: *** [all] Error 2
> Fix MacOSX cmake missing symbol _clock_gettime

- crypto/compat/getprogname_linux.c
This diff fixes the build of LibreSSL for Android with API < 21 where
the `getprogname` system call was not part of libc.
A comment in the diff itself explains in detail the issue.
I'm submitting this diff after I did a full build of LibreSSL [1] and
other software we're using, plus smoke testing.
.. [1] https://github.com/measurement-kit/script-build-android/releases/tag/v0.10.2-1
> Fix getprogname_linux.c for Android API < 21

- crypto/compat/getprogname_linux.c
cause problems on musl systems. Reference to https://github.com/libressl-portable/portable/issues/528
> avoid glibc

- CMakeLists.txt
Prevents LibreSSL from generating it's own uninstall target if one already exists. In big CMake projects there is usually one already defined and will cause a error similar to this:
```
1> [CMake] CMake Error at Build/x64-Debug/_deps/libressl-src/source/CMakeLists.txt:259 (add_custom_target):
1> [CMake]   add_custom_target cannot create target "uninstall" because another target
1> [CMake]   with the same name already exists.  The existing target is a custom target
1> [CMake]   created in source directory
```
> Check for existing uninstall target before creating.

- crypto/compat/arc4random.h
- include/compat/machine/endian.h
- m4/check-os-options.m4
The routines inside arc4random_linux also apply to midipix.
> initial support for midipix

- tls/CMakeLists.txt
- tls/Makefile.am
This PR is for issue https://github.com/libressl-portable/portable/issues/556 .
Refer to the commit https://github.com/libressl-portable/openbsd/commit/461e241c9b6c0a199a3f128d34ec82a7f2cc1cab , too.
> Override the default path of cert.pem in libtls

- FindLibreSSL.cmake
The function 'FindPackageHandleStandardArgs' needs to be included before used.
Addresses Issue #559 
https://github.com/libressl-portable/portable/issues/559
> Include FindPackageHandleStandardArgs before use.

- crypto/Makefile.am
gost/gost.h will go into include/openssl/, no need to duplicate it into crypto/gost directory
Signed-by: Dmitry Baryshkov <dbaryshkov@gmail.com>
> crypto: do not include gost.h into noinst_HEADERS

- crypto/Makefile.am
Make crypto_portable.sym depend on crypto.sym and libcrypto.so on
crypto_portable.sym to rebuild library if one of symbol files changes.
Signed-off-by: Dmitry Baryshkov <dbaryshkov@gmail.com>
> crypto: regenerate crypto_portable.sym

- crypto/CMakeLists.txt
- crypto/compat/posix_win.c
- include/compat/unistd.h
Since it seems only MSVC lacks sleep(), and it's only used by apps, lets special-case that and make it available as a static inline function instead. This fixes linkage issues where the target app also defines a sleep() compatibility function.
> avoid exporting a sleep() symbol from libcrypto

- CMakeLists.txt
- appveyor.yml
In certain contexts LibreSSL needs to be built with `/MT` instead of `/MD` for inclusion in other projects. These changes allow for the command-line option `USE_STATIC_MSVC_RUNTIMES` to be set to `ON` if the use wishes to generate projects that will build with static runtimes.
This feature requires CMAKE version 3.15+, hence the minimum required version has changed as well.
> Add support for use of static MSVC runtimes

- CMakeLists.txt
- tap-driver.sh
…also, fixed indentation in its `if`/`else` block; and in [tap-driver.sh] Updated copyright line (was automatic when I ran `./autogen.sh`)
The `CMakeLists.txt` reordering resolving this warning:
```
CMake Warning (dev) at /share/cmake/Modules/GNUInstallDirs.cmake:225 (message):
Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
target architecture is known.  Please enable at least one language before
including GNUInstallDirs.
```
> [CMakeLists.txt] Move `project` below `cmake_minimum_required`;

- appveyor.yml
- tests/testssl.bat
Modify testssl.bat to run ssltest on appveyor.
It appears that some sort of batch file command freezes on appveyor.
And, I added another commit to keep testing log as an artifact, since it helps test failure investigation.
I separated these 2 changes into another commits respectively.
My main proposal is ssltest, and if keeping log is not good, I would like to drop that commit.
> fix ssltest to run on appveyor, keep test log as artifact

- .gitignore
- crypto/CMakeLists.txt
- crypto/Makefile.am
- tests/CMakeLists.txt
- tests/Makefile.am
- update.sh
This PR is
- Add x509_verify.c x509_verify.h
- Restrict cipherstest with static build only in CMake, since it changes to use internal function
- Add regress x509_info.c
- Update .gitignore for some files in tests
> Add x509_verify.c x509_verify.h

- .gitignore
- apps/nc/Makefile.am
- apps/ocspcheck/CMakeLists.txt
- apps/ocspcheck/Makefile.am
- crypto/Makefile.am
- update.sh
This fixes a couple of issues, one adding a strtonum dependency in check, and a fix for #626 where nc(1) is unconditionally linked to libcrypto.a, but it might not always be built.
> Build fixes for static compatibility dependencies

- CMakeLists.txt
- apps/nc/CMakeLists.txt
- crypto/CMakeLists.txt
- ssl/CMakeLists.txt
- tests/CMakeLists.txt
- tls/CMakeLists.txt
This PR makes linking libcrypto and libssl to libtls statically with CMake build.
To enable this, applied cmake object library functionality to libcrypto, libssl, libtls, respectively, by first commit.
Cmake object library is a group of compiled object files, and it can be linked to generate shared/static library.
By second commit, libtls is generated by linking these cmake object libraries.
This libtls needs to export compat functions that currently exported from libcrypto.
To enable this, variable `EXTRA_EXPORT` is set to PARENT_SCOPE as `LIBTLS_EXTRA_EXPORT` and passed to tls/CMakeLists.txt.
`LIBTLS_EXTRA_EXPORT` is used to generate new `tls.sym` file.
`nc` and libtls regression tests are changed to link only with libtls.
> Statically link libcrypto/ssl into libtls with cmake

- .travis.yml
- scripts/travis
Android CI build had been failing because of some SDK and NDK changes.
This PR re-enable it again.
This time, restrict the target version to 8.0 (API level 26) and above
since older version appears to finish support already.
Build x86_64, x86, armv8, and removed armv7 build.
I thought to update platform to bionic, but Travis-CI Android builds seems
to be supported on trusty only at this time still.
https://docs.travis-ci.com/user/languages/android/
- Targeted to Android 8.0 (API level 26) and above
- Build for x86_64, x86 and arm64-v8a, stop searching dir for detecting ABI
- Use newer version of ndk and cmake
- Suppress sdkmanager messages to reduce log output
- Add log messages to tell CI running right
> Fix Android CI

- .gitignore
- tests/CMakeLists.txt
- tests/Makefile.am
- fix .gitignore for cert.pem, .cnf files and tests/ec_point_conversion
- re-enable clienttest
- add tlslegacytest
- add ssl_get_shared_ciphers
> Fix .gitignore and add tests

- .travis.yml
- scripts/travis_failure
- tests/CMakeLists.txt
- tests/Makefile.am
- tests/dtlstest.sh
This PR adds regression dtlstest.
And I added after_failure script to dump failed test log by second commit,
since I sometimes saw dtlstest failed.
I would like to see if dtlstest runs successfully by this PR.
> Add dtlstest

- CMakeLists.txt
This change allows libressl to be built with clang-cl.
> cmake: tweak for clang-cl

- m4/check-hardening-options.m4
- m4/check-os-options.m4
- tests/Makefile.am
I believe this PR would solve #649 and MinGW build failure on ubuntu 20.04 in #672 .
I saw "undefined reference to `__memcpy_chk'" error while building on ubuntu 20.04.
ubuntu 20.04 appears to install MinGW 7.0.0, and it requires to link libssp if we define "-D_FORTIFY_SOURCE=2".
I also disabled dtlstest with MinGW since it does not have poll.
> Fix mingw build on ubuntu 20.04

- include/compat/arpa/nameser.h
- include/compat/machine/endian.h
- include/compat/netinet/ip.h
- include/compat/resolv.h
- m4/check-libc.m4
I've successfully been shipping LibreSSL on Sortix for years now, a new system that doesn't yet have so many extensions beyond core POSIX, and these are my local patches that applies to libressl-portable suitable for upstreaming. This change helps LibreSSL handle systems without some non-essential and non-POSIX headers.
The `arpa/nameser.h`, `netinet/ip.h`, and `resolv.h` headers are not crucial to building LibreSSL. This change avoids including them if they're not around. The `netinet/ip.h` header is used in `nc(1)` for optional `IPTOS_` features that can be ifdef'd on systems without support (but that source file is not part of libressl-portable).
The `endian.h` header is the upcoming standard header and should be used whenever available and correct. The `machine/endian.h` header is …
> Support operating systems without some non-POSIX headers

- m4/check-os-options.m4
Compiler switch -mlp64 (GCC) or +DD64(HP CC) gives build failure with
platform HP-UX other than IA-64.
This avoids build break on HP-UX with PA-RISC platform.
Suggested from Larkin Nickle (me <at> larbob org) by libressl ML.
https://marc.info/?l=libressl&m=163649798619783&w=2
> Set IA-64 compiler flag only if it is HP-UX with IA-64

- apps/nc/CMakeLists.txt
- apps/ocspcheck/CMakeLists.txt
- apps/openssl/CMakeLists.txt
- crypto/CMakeLists.txt
- ssl/CMakeLists.txt
- tests/CMakeLists.txt
- tls/CMakeLists.txt
This could remove recurring of the same statement for include directories.
Instead of this removals, apps/* and tests  should have include path that
had been provided by INTERFACE_INCLUDE_DIRECTORIES of target libs and
internal static libs.
> Remove unneeded target_include_directories with cmake

- tests/CMakeLists.txt
- tests/Makefile.am
- Add regress ssl_methods to cmake
- Sort regress key_schedule in Makefile.am
- Fix _PATH_SSL_CA_FILE for ocsp_test
> assort tests cleanup

- ssl/Makefile.am
'ar d' command gets error on macos if specified object not exist.
> Ignore ar command error

- apps/nc/CMakeLists.txt
- apps/nc/Makefile.am
- apps/ocspcheck/CMakeLists.txt
- apps/ocspcheck/Makefile.am
- apps/openssl/CMakeLists.txt
- apps/openssl/Makefile.am
- crypto/CMakeLists.txt
- crypto/Makefile.am
- tests/optionstest.c
- update.sh
crypto library requires strtonum now, and add it to compat library.
remove it from applications compat/ directories.
> Add strtonum to compat library and export it

- .gitignore
- tests/CMakeLists.txt
- tests/Makefile.am
This adds two regress tests, evp_pkey_check and rfc3779.
> Add two regress tests

- apps/nc/compat/sys/socket.h
- include/compat/sys/socket.h
This fixes nc failing to run on darwin due to it incorrectly setting the
linux-specific SOCK_NONBLOCK flag on connect.
nc already had a portability shim in apps/nc/compat/sys/socket.h, which
kicks in if SOCK_NONBLOCK is undefined. But that header includes
include/compat/sys/socket.h, which also has a portability shim that
defines a default value for SOCK_NONBLOCK if it's undefined. Thus the
first portability shim was unreachable.
Fixes this by moving the NEED_SOCKET_FLAGS flag into the outer shim, and
having the inner shim activate if NEED_SOCKET_FLAGS is defined.
This closes https://github.com/libressl-portable/portable/issues/631
> Fix unreachable nc portability shim

- .github/workflows/macos_test.yml
- appveyor.yml
- scripts/test
- Add environment macos-12 to CI
- Set max number of processes for CI
- Use current VS2019 with appveyor
I also tried to add Android 12(API level 31), but it was not available still.
> Update CI actions

- patches/windows_headers.patch
Experimental PR for talking about #734 .
I would like to see if this does not any harm for a while.
On Windows with targeting the MSVC ABI, Clang will define _MSC_VER,
and does not treat __attribute__ as a macro.
Clang's builtin headers (e.g. immintrin.h) use __attribute__ liberally,
and do not expect it to be ifdef-ed away.
Suggested from Nicholas Hutchinson by github issue.
> Stop disabling __attribute__ on Windows with Clang

- CMakeLists.txt
- include/compat/endian.h
- m4/check-libc.m4
This pr fixes issue #749 by detecting `machine/endian.h` and trying to include it in `include/compat/endian.h`.
> Detect machine/endian.h for macOS

- .github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where libressl already runs. CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>
> CI: add CIFuzz action

- tests/Makefile.am
- tls/Makefile.am
- update.sh
Build and link a special test library rather than assuming that the build has static libraries available. This uses the same approach as libtls does for linking libcrypto/libssl in statically.
This also fixes #754 and replaces #765
> Build a static test library with all symbols

- crypto/CMakeLists.txt
- crypto/Makefile.am
- ssl/CMakeLists.txt
- ssl/Makefile.am
- tls/CMakeLists.txt
- tls/Makefile.am
- update.sh
Fix library generation with some CMake generators by including a direct source file dependency for each library. This is a small variation on #776 that includes libtls
> add direct source dependency to each library

- patches/crypto_namespace.h.patch
- patches/libcrypto.hidden.patch
- patches/libssl.hidden.patch
- patches/opensslfeatures.h.patch
- patches/ssl_namespace.h.patch
We need the __attribute__ workaround still in a public header, or you can't use the result in any MSVC project anyway.
This also adds more #include_next workarounds for MSVC's lack of that feature.
> Fix build for MSVC

- .github/workflows/linux_test_asan_noasm.yml
- scripts/test
This pull request adds a GitHub Actions workflow to run tests with ENABLE_ASM=off and ASAN enabled.
> Add CI workflow to run tests with ASM disabled

- ChangeLog
- patches/x509_vpm.c.patch
This is a port of a patch by Christian Heimes and fixes an issue flagged by Quentin Pradet: https://bugs.python.org/issue43522
> Fix urllib3 CN without SAN tests for LibreSSL 3.7

- tests/CMakeLists.txt
- tests/Makefile.am
These were broken with the removal of TLS 1.0/1.1 support due to static checks in packet structure.
> disable client / server tests for now

- apps/nc/CMakeLists.txt
- apps/ocspcheck/CMakeLists.txt
- apps/openssl/CMakeLists.txt
- crypto/CMakeLists.txt
- include/CMakeLists.txt
- ssl/CMakeLists.txt
- tests/CMakeLists.txt
- tls/CMakeLists.txt
This fixes #871 for CMake so we are not modifying the source directory unnecessarily. This also stops installing all of the arch-specific includes.
> generate opensslconf.h in build dir for cmake

- .github/workflows/macos_test.yml
- CMakeLists.txt
- scripts/test
Fixes #876 by adding the ability to specify one architecture at a time for CMAKE_OSX_ARCHITECTURES at least. Also add Ventura and Apple silicon compile checks to test matrix, removing Big Sur and gcc, which I think has been clang anyway for a while.
> Fix cross compile macos

- tests/CMakeLists.txt
- tests/Makefile.am
failure in ASAN was unrelated to tls 1.0/1.1 changes
> reenable ssltest

- .github/workflows/macos_test.yml
- .github/workflows/windows_test.yml
- tests/testssl.bat
This can replace Appveyor, and has some benefits in that all the folks in this project can also see the results directly, and we can use this to push build artifacts to the releases.
Also tacks on a small tweak to macOS builds so you can tell them apart by architecture.
> Add Windows builds to Github actions

- tls/Makefile.am
This solves a problem where a program, such as opensmtpd, may need to modify the state of libcrypto, but have a surprising effect when this does not affect the crypto code that libtls is using, since it is a standalone copy.
This changes build behavior introduced in 2020 back to dynamically linking libtls to libssl/libcrypto by default, but the existing --enable-libtls-only flag will still build a fully self-contained library. However, note that linking libcrypto/libssl to a binary using a standalone libtls will cause libtls to always use its internal crypto/tls code, instead of that from the external libraries.
> only link libtls statically to libssl/libcrypto when building standalone

- include/compat/stdint.h
- include/compat/sys/types.h
There's not a great place for these, but since they are internal, we can just move them to the most common header.
> move attribute shims

- README.md
- include/compat/endian.h
- update.sh
Solaris 10 has probably been broken for a while, and we don't really have the motivation or resources to support it. While we're at it, fix Solaris 11 as well (tested on Solaris 11.4).
> see #353, Solaris 11 fixes, make minimum supported version

- CMakeLists.txt
- crypto/compat/posix_win.c
Fixes #266 based on discussion in that issue and the approach used by Python here https://bugs.python.org/issue23524, adjust the compat layer for Windows to use [_get_osfhandle](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/get-osfhandle?view=msvc-170) in combination with
[_set_thread_local_invalid_parameter_handler](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/set-invalid-parameter-handler-set-thread-local-invalid-parameter-handler?view=msvc-170) if applicable to more reliably determine if a handle is a socket, file, or closed socket, without causing an exception at the same time leading to a crash.
This prevents assertions when calling tls_close on an already-closed socket.
I was experimenting with whether this is needed on mingw-w64, but its CRT …
> change socket / file descriptor checks on windows

- .github/workflows/solaris_test.yml
This adds a builder for Solaris 11.4 based on https://github.com/vmactions/solaris-vm
This takes about an _hour_ to run, so it's configured to only run on merges/pushes rather than PRs.
> initial solaris test workflow

- .github/workflows/cifuzz.yml
Since fuzzers benefit more from being run regularly on the openbsd tree, and they take a long time, does it make more sense that the trigger is a cron like the Coverity job? They sometimes don't work in branches anyway, since the fuzz builds rely on external code being updated to match the master branch.
> change the trigger for running fuzzer tests

- CMakeLists.txt
A variation from https://www.kitware.com/cmake-and-the-default-build-type/ to default to enabling optimizations if no build type is specified.
> set default build type to 'Release'

- .github/workflows/fedora-rawhide.yml
Fedora Rawhide is shipped with the most recent gcc/clang, it is nice to test build on them from time to time
> CI: add scheduled Fedora Rawhide builds

- crypto/Makefile.am
- include/Makefile.am
This fixes #908 by including getopt compat files with the release package.
> package getopt compat files

- CMakeLists.txt
- LibreSSLConfig.cmake.in
`check_required_components` does not take a list of components; it takes the package name and determines if a component is available by checking the `<package>_<component>_FOUND` variable.  Without this change, `find_package(LibreSSL REQUIRED COMPONENTS Invalid)` would succeed despite that component not existing.
This change also makes `LIBRESSL_FOUND` mirror the `LibreSSL_FOUND` variable that cmake uses internally to check if the package exists, and changes the `install` source paths of the cmake files to match the ones they were configured with.
> Cmake improvements

- m4/check-os-options.m4
> enable system arc4random on FreeBSD 12+

- patches/windows_headers.patch
> Allow disabling warning about WINCRYPT overrides

- crypto/compat/ui_openssl_win.c
Fixes:
```
./libressl/crypto/ui/ui_openssl_win.c:134:15: warning: unused variable 'savsig' [-Wunused-variable]
134 | static void (*savsig[NX509_SIG])(int );
|               ^~~~~~
1 warning generated.
```
Follow-up to dd1d96f643b01a5edbe7e0db8399f3c88f5f0c8b
Fixes #925
> delete unused `savsig` variable on Windows

- tls/CMakeLists.txt
By dropping copies of `libcrypto` and `libssl` lib objects from it.
This brings back its size to the normal ~100KB from ~4MB.
autotools already worked like this.
> slim down `libtls`

- CMakeLists.txt
- tls/CMakeLists.txt
Instead of including a full copy of libcrypto and libssl in libtls-static, link existing libcrytpo-static and libssl-static to the test targets.
This wasn't causing any issue, just unnecessarily duplicating a lot of objects.
> slim `tls-static` library (used in tests)

- patches/win32_amd64_bn_arch.h.patch
Fixes this warning when `OPENSSL_NO_ASM` is already set by the build system (seen with CMake):
```
In file included from ./crypto/bn/bn_mul.c:65:
./crypto/bn/arch/amd64/bn_arch.h:24:9: warning: 'OPENSSL_NO_ASM' macro redefined [-Wmacro-redefined]
^
<command line>:10:9: note: previous definition is here
^
```
Reported in #910
> amd64/bn_arch.h: avoid redefinition of `OPENSSL_NO_ASM`

- README.md
Update the workflow badge images to use the new workflow names introduced in: #942, #941, #934
Once I have cleaned up more workflow files, I will make another pull request to update the rest of the badges.
> readme: fix CI workflow badge images

- .github/workflows/rust-openssl.yml
Change around the order slightly. It seems more logical to apply the patch first, then export the env.
> Fix rust-openssl regress

- .github/workflows/cifuzz.yml
- .github/workflows/solaris_test.yml
- README.md
Neither of these has built in over a month.
Solaris looks to be an upstream timeout issue (seems the hack it uses may not work anymore).
https://github.com/libressl/portable/actions/runs/6999379749
Not sure if cifuzz is really needed either, since we're still being tested through clusterfuzz actively.
https://github.com/libressl/portable/actions/runs/7012733325
> disable periodic builds of broken CI workflows

- crypto/compat/ui_openssl_win.c
- m4/check-os-options.m4
- tap-driver.sh
Also delete a broken link, with no archive.org or other online 
copy that I could dig up.
> upgrade links in comments to HTTPS

- CMakeLists.txt
Notice that just like in autotools, this detection also doesn't take
into account the targeted OS version. Meaning it detects `strtonum` even
if targeting e.g. macOS older than release v11 Big Sur (which introduced
this funcitions), if the SDK declares it. Wrong detection will either
cause a binary broken on older macOS and/or trigger compiler warnings.
Ref: https://github.com/libressl/portable/issues/928#issuecomment-1850178282
Ref: https://github.com/libressl/portable/issues/928#issuecomment-1850276298
Prerequisite: #961
> cmake: auto-detect `strtonum`

- include/compat/pthread.h
You can't pass a function pointer through a void pointer. So wrap the pthread callback in a struct.
Fixes #966
> pthreads.h: avoid undefined behavior

- .github/workflows/fedora-rawhide.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/rust-openssl.yml
- .github/workflows/solaris.yml
- .github/workflows/windows.yml
it's pretty annoying to get weekly reports that your fork is out of sync and some files are missing
but those run make sense for original repo
> CI: limit scheduled runs to "libressl" org only

- CMakeLists.txt
This method allows to set it via custom flags.
> cmake: disable default NDEBUG differently

- crypto/compat/posix_win.c
Hi, 
I tried to run the test suite in Debug mode on windows and had an assertion window pop. 
It happens when running the signertest, or the test project in  https://github.com/libressl/portable/issues/266. This was fixed in afcd4be8a72a for a release compiled library. To prevent the issue in debug mode, it looks like it is necessary to  also disable the assertion window popup. 
With this all tests pass when compiling and running them with a Debug, Release or RelWithDebInfo CMake build on windows (for me).
> Windows: Prevent assertion pop-up up when using Debug compiled libressl.

- CMakeLists.txt
Hi, I noticed that -Wall is set when using visual studio, which enables a lot of spammed warnings like these (which are not part of the W4):
This reduces the warnings to W4, which are the ones that CI appears to use, if it makes sense.
> Windows: Don't set -Wall when compiling with Visual Studio.

- CMakeLists.txt
- include/compat/endian.h
Hi,
I noticed that ´__BYTE_ORDER__´ was not defined when compiling with visual studio, causing it to detect everything as little endian. This adds a cmake build check for endianness, if you think it makes sense to do this.
Visual studio does not define ´__BYTE_ORDER__´  so all architectures were detected as LITTLE_ENDIAN since both ´__BYTE_ORDER__´ and ´__ORDER_LITTLE_ENDIAN__´ would evaluate to 0 and compare equal. This updates the checks to use CMakes detection of endianness, with a hard error, if this also fails.
> Windows: Improve check for endianness when using Visual Studio.

- .github/scripts/changelog.sh
during CI stdout is redirected to "changelog.txt" and thus not seen
> CI: redirect changelog error to stdout

- include/compat/cet.h
- update.sh
Try 2, it's difficult for now to remove the cpp dependency. Testing a cet.h shim which at least prevents us from leaking some host system details during the code generation phase.
> deal with masm in a compatible way with openbsd's cpp

- .github/workflows/windows.yml
Noticed a failure in appveyor with shared libs enabled, do the same in workflows
> test windows builds with shared libs enabled

- crypto/CMakeLists.txt
Was getting this linker error building shared libraries on Windows:
```
Creating library C:/projects/portable/build/ssl/Release/ssl.lib and object C:/projects/portable/build/ssl/Release/ssl.exp
recallocarray.obj : error LNK2019: unresolved external symbol getpagesize referenced in function
```
getpagesize should be in compat rather than crypto object file list.
> put compat getpagesize into the right object list

- .gitignore
As 37d868b and 04fa997 added two new tests, this patch adds them to the gitignore to prevent from pushing copied files.
> Add `tests/bio_dump*` and `tests/x509_algor*` to gitignore

- .github/workflows/linux.yml
This reverts commit cb2fd0abb21fc2ed4a725de0c57df25e10eee7e8 from #1019.
> Revert "CI: setup kernel entropy to work with asan"

- libtls.pc.in
Since d193f43 ("slim down `libtls`"), statically linking libtls requires also linking libssl and libcrypto, so express that in the pkg-config file.
> Add libssl and libcrypto to libtls's Libs.private

- CMakeLists.txt
Collapse the same if condition blocks into one block.  Include the uninstall rule when building install rules; if there was no install, shouldn't need uninstall (for this build; a previous build that was installed would have an uninstall rule).
There were several if( ENABLE_LIBRESSL_INSTALL ) in a row, hence the deleted endif()/if( ENABLE_LIBRESSL_INSTALL ) lines.
> Modify CMake rules to only build uninstall if install is enabled

- crypto/CMakeLists.txt
- crypto/Makefile.am.mingw64-x86_64
- https://github.com/libressl/openbsd/pull/149 fixes to crash
on startup issue, thus nuking all endbr opcodes is no longer
necessary. This effectively enables CET in ASM code for
MinGW x86_64 builds.
A broader fix landed now via:
https://github.com/openbsd/src/commit/db9cd57725789270c36763286ca8dc0a7c1b9d10
- llvm `cet.h` (as of v18) assigns `endbr32` instead of `endbr64`
to `_CET_ENDBR` macro for MinGW x86_64 targets.
https://github.com/llvm/llvm-project/blob/llvmorg-18.1.1/clang/lib/Headers/cet.h#L15-L35
Work this around by mapping `endbr32` to `endbr64`.
Prerequisite: https://github.com/libressl/openbsd/pull/149
Fixes: https://github.com/libressl/portable/issues/1015
> mingw: re-enable endbr opcode, add workaround for llvm `cet.h` issue

- update.sh
Some systems (e.g. OpenBSD) unconditionally set __CET__ in the C preprocessor, which we don't want for masm yet. Eventually we need to figure out how to use the VS C preprocessor on assembly directly. This already went into the stable branches in #1033
> explicitly undef __CET__ on masm cpp

- scripts/test
- update.sh
This avoids issue reported in #1041 with file glob confusing `cd` in some cases.
Also remove extra newline from VERSION when update.sh runs.
> use a specific version number in test scripts

- configure.ac
- m4/check-os-options.m4
Fixes #1055 by failing earlier in the configuration process. Removes a long-dead BSD platform.
> Remove dead bitrig support, error on unsupported platforms

- crypto/compat/posix_win.c
When compiling in release mode the _CrtSetReportMode macro gets replaced by void(0). This makes old_report_mode unused, which visual studio warns about.
> [Windows] Mark old_report_mode as unused

- README.md
This PR adds Emscripten in the list of compatible operating systems. Additionally, it provides a note on using `emcmake` for configuring LibreSSL with Emscripten.
> Add Emscripten Compatibility and Configuration Note

- .github/workflows/windows.yml
- CMakeLists.txt
- crypto/CMakeLists.txt
- ssl/CMakeLists.txt
- tls/CMakeLists.txt
> Append version to dll on CMake

- apps/openssl/compat/poll_win.c
- crypto/compat/posix_win.c
- include/compat/sys/time.h
> Attempt to fix 2038 problem with MSVC

- tests/CMakeLists.txt
- tests/Makefile.am
> Link err_test to build

- CMakeLists.txt
FreeBSD's libc has a stub implementation of pthread_once() that returns ENOSYS and doesn't seem to call the init routine. You need to link with pthread for this to work.  This PR does this and fixes regress failures for CMake builds on this platform.  This likely never worked.
> Fix CMake build on FreeBSD

- .github/workflows/freebsd.yml
Add a GitHub Actions workflow to run `make check` inside a FreeBSD VM, which runs daily at 00:00 or when manually requested.
This is similar to the Solaris VM workflow, and uses an action from the same `vmactions` org.
Successful CI run:
https://github.com/joshuasing/libressl-portable/actions/runs/11341234538/job/31539126298
Should this also run `gmake test` or similar?
> ci: add freebsd workflow

- crypto/compat/posix_win.c
> Make gettimeofday() definition match the prototype

- configure.ac
- m4/check-os-options.m4
There's a lot of new Unix-like operating systems out that that might port LibreSSL (my Sortix is among them) and they all use ELF. If the operating system doesn't use ELF or isn't an Unix, it doesn't have a chance at working out of this box anyway, and this change makes LibreSSL work on a generic and sufficiently featured POSIX system.
> Assume unknown operating systems use ELF.

- patches/tls_config.c.patch
uid_t on Sortix is 64-bit.
I'm unclear if PRIu64 exists on Visual Studio like you suggested if %llu doesn't work. If not, then we could compat header inttypes.h and add a fallback definition for MSVC that surely has another sequence that does it.
... It might be easier to just drop the uids from the error message. "session file has incorrect owner" is clear enough.
> Print uid_t portably with PRIu64.

- CMakeLists.txt
- crypto/CMakeLists.txt
- ssl/CMakeLists.txt
Append additional MSVC warnings to `MSVC_DISABLED_WARNINGS_LIST`.
> Disable additional MSVC warnings

- FindLibreSSL.cmake
The Homebrew package manager commonly used on macOS places LibreSSL in a known location, so this patch adds that directory to the search list in the CMake find script.
This makes it so macOS users do not have to directly set LIBRESSL_ROOT_DIR if they have installed it using Homebrew.
> Added CMake hint when searching for LibreSSL directory on macOS

- .gitignore
- tests/CMakeLists.txt
- tests/Makefile.am
- tests/mlkem1024_decap_tests.sh
- tests/mlkem1024_encap_tests.sh
- tests/mlkem1024_iteration_test.sh
- tests/mlkem1024_keygen_tests.sh
- tests/mlkem1024_nist_decap_tests.sh
- tests/mlkem1024_nist_keygen_tests.sh
- tests/mlkem768_decap_tests.sh
- tests/mlkem768_encap_tests.sh
- tests/mlkem768_keygen_tests.sh
- tests/mlkem768_nist_decap_tests.sh
- tests/mlkem768_nist_keygen_tests.sh
- update.sh
This patch adds ML-KEM related tests.
> Hook ML-KEM related tests

- .github/workflows/linux.yml
- scripts/test
Since `scripts/test` always unset "CC", the github action for "clang"
in Linux does not use clang unintentionally.
This patch unset CC only for mingw{32,64} and arm32.
> unset CC only for mingw and arm32

- include/compat/endian.h
Apple SDKs indeed have the endian.h headers, but they do not contain these functions and therefore will error out when doing a cmake build. Remove the conditional HAVE_ENDIAN check or remove the conditional check for Apple compatibility? I chose to remove the conditional check for Apple compatibility.
> Add in missing endianess functions for Apple targets

- .github/workflows/android.yml
- .github/workflows/cifuzz.yml
- .github/workflows/cmake_config.yml
- .github/workflows/coverity.yml
- .github/workflows/emscripten.yml
- .github/workflows/fedora-rawhide.yml
- .github/workflows/freebsd.yml
- .github/workflows/linux.yml
- .github/workflows/release.yml
- .github/workflows/rust-openssl.yml
- .github/workflows/solaris.yml
Actions have been issuing annoying warnings about ubuntu-24.04 becoming the default for ubuntu-latest for some definition of "soon". Let's see if we care.
> What happens on ubuntu-24.04?

- .github/workflows/linux.yml
- scripts/test
Add support for testing on `loongarch64` in the `/scripts/test` script and in GitHub Actions. This works by using GCC cross-compilation and QEMU to build and run the tests.
Currently compilation on `master` will fail, so this should be merged only after #1146 is merged.
Tested locally on #1146, all tests pass and the `file` output shows LoongArch:
```
============================================================================
Testsuite summary for libressl 4.1.0
============================================================================
============================================================================
make[3]: Leaving directory '/libressl/tests'
make[2]: Leaving directory '/libressl/tests'
make[1]: Leaving directory '/libressl/tests'
make[1]: Entering directory '/libressl' …
```
> ci: test on loongarch64

- .gitignore
The arch/ directory is regenerated by autogen.sh and should generally be ignored. Only the mips and loongarch64 subdirectories are tracked in the portable tree because they are not supported by OpenBSD natively, but there has been interest in using LibreSSL on these architectures.
Fix https://github.com/libressl/portable/issues/1160
> .gitignore: ignore crypto/arch/* except for mips and loongarch64

- tests/CMakeLists.txt
- tests/Makefile.am
This change cleans up the old test infrastructure in preparation for consolidating the x509name.c test logic into x509_name_test.c.
Update CMakeLists.txt and Makefile.am accordingly.
> Remove x509name test in preparation for merge into x509_name_test.c

- crypto/CMakeLists.txt
- crypto/Makefile.am.elf-x86_64
- crypto/Makefile.am.macosx-x86_64
- crypto/Makefile.am.masm-x86_64
- crypto/Makefile.am.mingw64-x86_64
- update.sh
Remove generation of vpaes and bsaes assembly sources from update.sh, as these are removed from source tree.
See: https://github.com/openbsd/src/commit/824f363240372afd9c86bea543128d656b531c16
> update.sh: stop generating vpaes and bsaes x86_64 assembly

- .github/workflows/rust-openssl.yml
In the GitHub Actions workflow for rust-openssl testing, apply the patch used in OpenBSD ports to support `EVP_PKEY_get1_*` APIs with const_ptr. This ensures that the build succeeds before the official version bump to LibreSSL 4.2.0.
Fix https://github.com/libressl/portable/issues/1187
> CI: Apply EVP const_ptr patch for LibreSSL < 4.2.0

- CMakeLists.txt
The CMake build does not define these macros, autoconf build does.  This fixes the CMake build and brings it on par with autoconf.
Fixes https://github.com/libressl/portable/issues/1189
> check for resolv.h and arpa/nameser.h

- apps/nc/compat/accept4.c
Fix inconsistencies in accept4.c. If the underlying accept() fails the shim returns the listening socket s instead of −1.
> Fix inconsistencies in accept4.c
