libressl/portable

.gitignore, gen-coverage-report.sh, tests/Makefile.am, tests/openssl.cnf, tests/optionstest.c, tests/testdsa.sh, tests/testenc.sh, tests/testrsa.sh
These are added directly rather than imported by update.sh since they require local modifications and its not worth breaking everyone's git forks yet to import them through cvs2git.
=> add app tests from regress/usr.bin/openssl

ChangeLog
=> Fix typo in the ChangeLog

patches/netcat.c.patch
I want to use it on osx 10.5 and 10.6.
Could you merge the pull request?
Thanks in advance,
Goichi
=> update netcat.c.patch for osx 10.6 or earlier

CMakeLists.txt
- add MINGW and CYGWIN for win build
=> add condition for setting BUILD_SHARED (cmake)

CMakeLists.txt, crypto/CMakeLists.txt
- add functionality compiling ASM with cmake
- to enable ASM, `cmake -DENABLE_ASM=on ..`
=> modify cmake to build ASM

tests/Makefile.am
to include ocsptest.sh into distribution tar.gz
=> include OCSP test script

libtls-standalone/src/Makefile.am, tls/CMakeLists.txt, tls/Makefile.am
see https://github.com/libressl-portable/openbsd/pull/64
as propsal for #146
=> Portable code part for callbacks in accept/connect

configure.ac, crypto/Makefile.am, m4/check-libc.m4
- generating platform specific crypto/crypto_portable.sym from crypto.sym
=> Fix to use -export-symbols for libcrypto

patches/netcat.c.patch
- Update patch for commit https://github.com/libressl-portable/openbsd/commit/3caa01b5c522093a003bd52c804c0148fdac3c5a
- This will fix https://github.com/libressl-portable/portable/issues/279
=> Fix patch for netcat.c

.gitignore, crypto/CMakeLists.txt, crypto/Makefile.am, crypto/compat/getpagesize.c, include/compat/stdlib.h, include/compat/unistd.h, m4/check-libc.m4, update.sh
This PR is initial support for using recallocarray.
We need to add getpagesize fix for VisualStudio and HP-UX.
=> Add recallocarray

.gitignore, tests/CMakeLists.txt, tests/Makefile.am, tests/servertest.bat, tests/servertest.sh
This PR adds 2 new regress tests.
- servertest
- tls_prf
=> Add 2 new regress tests

patches/http.c.patch
indicated by Kyle J. McKay mackyle@gmail.com
=> defining DEFAULT_CA_FILE only if it is not defined.

m4/check-os-options.m4
=> Set Solaris build default to 64 bit

crypto/CMakeLists.txt, crypto/Makefile.am
For commit https://github.com/libressl-portable/openbsd/commit/608832dd04dc9320413c86bf90576f2eb6a886b9
=> Remove rsa/rsa_ssl.c

apps/ocspcheck/CMakeLists.txt
- Issue #352 pointed out by @d3x0r
=> Fix checking memmem in apps/ocspcheck/CMakeLists.txt

update.sh
Make it easier to install only one section
=> Separate man(5) pages

include/compat/time.h
=> add timerspecsub compat implementation

.gitignore, tests/CMakeLists.txt, tests/Makefile.am
- Add regress asn1evp
- Add regress configtest
=> Add regress asn1evp and configtest

include/compat/sys/time.h
This Pull Request is for HP-UX build.
=> Add CLOCK_MONOTONIC and timersub for the OS that does not have them

apps/ocspcheck/Makefile.am
=> Install ocspcheck.8 manual

crypto/CMakeLists.txt, ssl/CMakeLists.txt, tls/CMakeLists.txt
=> Fix target properties when building static libs

.travis.yml, scripts/travis
- Fix android build
- Add android 10 build
=> Fix android build

tests/testssl.bat
Fix for #598 
I had confirmed that this PR fixed the ssltest error.
=> Test both SSLv3 and TLSv1.2, select cipher suite that the protocol can handle

configure.ac, include/compat/machine/endian.h
=> Get __STRICT_ALIGNMENT from machine/endian.h

include/compat/pthread.h
This takes the dynamic initialisation code added to CRYPTO_lock() in e5081719
and applies it to the Window's pthread_mutex implementation. This allows for
PTHREAD_MUTEX_INITIALIZER to be used on Windows.
bcook has agreed to place this code in the public domain (as per the rest of
the code in pthread.h).
=> Make pthread_mutex static initialisation work on Windows.

.travis.yml, scripts/travis, tests/CMakeLists.txt
Ubuntu Trusty repos have disappeared and are now end-of-support, so bump to Bionic.
=> update to Ubuntu 18.0.4 LTS for CI testing

libcrypto.pc.in, libssl.pc.in, libtls.pc.in
This PR is not urgent and just clean up pc files.
- Remove `Requires:` and `Conflicts:`
- libssl.pc does not need to have `Libs.private:` since `Requires.private:` provides required
=> Update pc files

.gitignore, tests/CMakeLists.txt, tests/Makefile.am
This PR adds several asn1 regresses.
=> Add asn1 related tests

configure.ac, m4/check-hardening-options.m4, tap-driver.sh
fix latest round of autotool complaints
=> update autotool macro deprecations

update.sh
=> Copy ARM related files from arch/arm/

scripts/config.guess, scripts/config.sub
config.sub and config.guess on LibreSSL are very old. To build LibreSSL on M1 Mac, we need to update config.sub.
=> update config.sub and config.guess for M1 Mac

OPENBSD_BRANCH, update.sh
Unbreak master branch while integrating latest upstream changes.
=> pin master build to upstream commit

update.sh
This is a compromise needed to support building from non-stable tags. This incorporates the same logic used to generate openbsd tags in the first place, which are unstable because the CVS to git conversion does not have stable commit hashes.
This should mostly fix #814, though it now includes a message noting that if you're not on a tag, it's possible the build will be broken from time to time when we do fresh syncs. This is normal and expected, but (future) tags should keep working.
=> Checkout openbsd tag or closest commit when on a release tag

crypto/CMakeLists.txt, crypto/Makefile.am.macosx-x86_64, update.sh
=> move endbr64 removal on macOS to preprocessor

.github/workflows/solaris_test.yml, README.md
Switch from build on push to daily, since this is so slow.
=> Solaris daily

include/compat/endian.h
=> Simplify and fix solaris endian.h macros

.github/workflows/solaris_test.yml
Update solaris vm to latest version
=> Update solaris vm to latest version

patches/windows_headers.patch
=> Stop undefining X509_CERT_PAIR

.github/workflows/linux.yml
couple of jobs were missed previously
=> CI: limit scheduled runs to "libressl" org only

.github/workflows/macos.yml
This patch adds test for macos-14.
=> Add tests for macos-14

README.md
So it is a bit easier to setup, without having to try and figure out why CMake is not generating a valid build. To try and improve #1044 :)
=> [Windows] Mention running update.sh in readme.

crypto/CMakeLists.txt, ssl/CMakeLists.txt, tls/CMakeLists.txt
Pointed out by @vszakats in #1100
=> Pull if() statement out of argument list

.github/workflows/macos.yml
https://github.com/actions/runner-images/issues/10721
=> CI: bump macos-12 to 15

crypto/compat/posix_win.c, include/compat/sys/stat.h
Just doing some testing to see if we can implement a fix for #1069 on top of #1071 using method suggested in https://github.com/libressl/portable/issues/266#issuecomment-2227664358
There are a handful of tests that already are failing in master on wine + mingw-w64, but pushing this to check other platforms through CI first.
=> Alt fix for #1069

tests/compat/pipe2.c
AppVeyor build: https://ci.appveyor.com/project/datadiode/portable/build/job/qx40dgjcwrd84n2m
=> Catch issue #1069 in signertest, tlstest

crypto/CMakeLists.txt, crypto/Makefile.am
just a test if we disabled it everywhere in advance of it being removed upstream
=> experiment with removing BIO_s_log in advance of upstream removal

.github/workflows/windows.yml
=> Update Windows CI runner to 2025

.github/workflows/linux.yml
reference: https://github.com/actions/partner-runner-images
=> CI: introduce ubuntu-24.04 on arm64
